# This dockerfile utilizes components licensed by their respective owners/authors.
# Prior to utilizing this file or resulting images please review the respective licenses at: http://www.apache.org/licenses/, https://secure.php.net/license/

FROM mcr.microsoft.com/windows/servercore:ltsc2022

LABEL Description="Apache-PHP" Vendor1="Apache Software Foundation" Version1="2.4.38" Vendor2="The PHP Group" Version2="8.1 TS"

RUN powershell -Command \
	$ErrorActionPreference = 'Stop'

COPY apache.zip /

#RUN	powershell -Command \
#    Expand-Archive -Path c:\apache.zip -DestinationPath c:\ ; \
#    Remove-Item c:\Apache24\conf\httpd.conf -Force ; \
#	Remove-Item c:\apache.zip -Force

COPY nginx.zip c:/

RUN	powershell -Command \
    Expand-Archive -Path c:\nginx.zip -DestinationPath c:\ ;
RUN powershell -Command Remove-Item c:/nginx-1.24.0/conf/nginx.conf
COPY RunHiddenConsole.exe C:/

RUN powershell -Command \
	$ErrorActionPreference = 'Stop'; \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Method Get -Uri https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile c:\vc_redist.x64.exe ; \
   	start-Process c:\vc_redist.x64.exe -ArgumentList '/quiet' -Wait ; \
   	Remove-Item c:\vc_redist.x64.exe -Force

RUN powershell -Command \
	$ErrorActionPreference = 'Stop'; \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Method Get -Uri https://windows.php.net/downloads/releases/archives/php-8.1.0-Win32-vs16-x64.zip -OutFile c:\php.zip ; \
	Expand-Archive -Path c:\php.zip -DestinationPath c:\php ; \
	Remove-Item c:\php.zip -Force

RUN powershell -Command \
	$ErrorActionPreference = 'Stop'; \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Method Get -Uri https://packages.blackfire.io/binaries/blackfire/2.5.0/blackfire-windows_amd64.zip -OutFile c:\blackfire.zip ; \
	Expand-Archive -Path c:\blackfire.zip -DestinationPath c:\blackfire ; \
	Remove-Item c:\blackfire.zip -Force

RUN setx path ";C:\php"

WORKDIR /nginx-1.24.0
COPY php_memcache.dll c:/php/ext
COPY php_blackfire.dll c:/php/ext
RUN setx path "%path%;C:\blackfire"
RUN blackfire agent:config --server-id=c0b4b4c5-1602-4fad-b126-816eaa8394d9 --server-token=6b62bed9febfd5e2a57014cfbf11c656cba3ac2579c0e2ae11249c8815b5e259
RUN sc.exe create Blackfire binpath="C:\Blackfire\blackfire.exe agent:start" start=auto depend=Tcpip/Dnscache
RUN echo 172.20.0.110 doajs.local.com >> "C:\Windows\System32\drivers\etc\hosts"
RUN powershell -Command \
    	$ErrorActionPreference = 'Stop'; \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; \
    Invoke-WebRequest 'https://www.libreoffice.org/donate/dl/win-x86_64/7.5.4/es/LibreOffice_7.5.4_Win_x86-64.msi' -OutFile libreOffice.msi -UseBasicParsing ; \
    Start-Process msiexec.exe -ArgumentList '/i', 'libreOffice.msi', '/quiet', '/norestart' -NoNewWindow -Wait
RUN setx path "%path%;C:\Program Files\LibreOffice\program"
#COPY httpd.conf c:/Apache24/conf/
COPY cacert.pem c:/php/extras/ssl
COPY php.ini c:/php
COPY php_xdebug.dll c:/php/ext
RUN SET PHP_FCGI_MAX_REQUESTS=0
COPY nginx.conf "C:/nginx-1.24.0/conf"
RUN powershell -Command new-item c:/www -ItemType Directory
RUN C:\RunHiddenConsole.exe C:\php\php-cgi.exe -b 127.0.0.1:9123
CMD ["c:\\nginx-1.24.0\\nginx.exe"]
